### ISSUE TITLE
AWS::EC2::Route should accept Token[CidrBlock] as DestinationCidrBlock

### ISSUE THREAD

**Issue by guoshimin** [MonsantoCo/cloudformation-template-generator#13]
Currently it only accepts a literal CidrBlock.

**Comment by ryan-richt** [comment]
Awesome, thank you, we will merge. 

Yeah I wonder if longer term I should refactor this whole mechanism so you can always pass an amazon function to anything? I wonder if there are any places we should enforce NOT being able to pass an amazon function..

**Comment by ryan-richt** [comment]
merged into develop, thank you Shimin!
