### ISSUE TITLE
Scala 2.12 Artifact

### ISSUE THREAD

**Issue by bpholt** [MonsantoCo/cloudformation-template-generator#130]
It looks like #122 added support for Scala 2.12, but I don't see an artifact published in JCenter. Am I just missing something or is publishing for 2.12 not enabled yet?

**Comment by bpholt** [comment]
Ok, I was missing something, but I think the documentation may be wrong.

The [README says](https://github.com/MonsantoCo/cloudformation-template-generator/blame/master/README.md#L23)

> To use this library, you must add the following resolver
> ```scala
> resolvers ++= Seq(Resolver.jcenterRepo)
> ```

When I changed the resolver to

```scala
resolvers ++= Seq(Resolver.bintrayRepo("monsanto", "maven"))
```

sbt was able to find the artifact.

If this is what you expected, I can make a PR to update the README accordingly.

**Comment by bkrodgers** [comment]
It should be there in JCenter, but I do see that it indeed is not.  I'll look at it next week.  Thanks for the heads up!

**Comment by bkrodgers** [comment]
I've got an email in to Bintray to get more details on what's going on here.  It looks like since there was only a 2.11 version when it was initially linked to JCenter from our Bintray space, it's not picking up the additional artifact.  Not seeing a way to fix it myself.  I'll keep you posted.

**Comment by bkrodgers** [comment]
This should now be resolved.  I see it under https://jcenter.bintray.com/com/monsanto/arch/cloud-formation-template-generator_2.12/.  You should no longer need the reference to `bintrayRepo("monsanto", "maven")` in your project.  If you remove that resolver and clear your ivy cache (`rm -rf ~/.ivy2/cache/com.monsanto.arch/`), you should see it re-download it from that path.  Let me know if it works for you.

**Comment by bpholt** [comment]
```
[info] downloading https://jcenter.bintray.com/com/monsanto/arch/cloud-formation-template-generator_2.12/3.5.1/cloud-formation-template-generator_2.12-3.5.1.jar ...
[info] 	[SUCCESSFUL ] com.monsanto.arch#cloud-formation-template-generator_2.12;3.5.1!cloud-formation-template-generator_2.12.jar (1528ms)
```

Looks good! Thanks for resolving it.
