### ISSUE TITLE
Support for Elastic Container Service/Registry entities

### ISSUE THREAD

**Issue by pyoio** [MonsantoCo/cloudformation-template-generator#132]
Hi, are there any plans to implement support for the ECS/ECR related entities (AWS docs [here](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html))? Specifically:

- `AWS::ECR::Repository`
- `AWS::ECS::Cluster`
- `AWS::ECS::Service`
- `AWS::ECS::TaskDefinition`

**Comment by tj-corrigan** [comment]
We haven't been adding many new features ourselves recently but are welcoming PRs if you would like to contribute.

**Comment by jfklingler** [comment]
Should this issue be closed since #142 was merged?

**Comment by bkrodgers** [comment]
Yep, good catch.  The PR didn't quite have the right keyword to get done automatically.
