### ISSUE TITLE
PolicyStatement Missing Sid Element required by SNS Topic Policy?

### ISSUE THREAD

**Issue by bpholt** [MonsantoCo/cloudformation-template-generator#138]
When I try to create an SNS Topic Policy that contains multiple policy statements, I get an error from CloudFormation: “Invalid parameter: Every policy statement must have a unique ID.”

Here's an example of the topic policy I'd like to create:

```scala
val topicPolicy = `AWS::SNS::TopicPolicy`("TopicPolicy",
  PolicyDocument = PolicyDocument(Statement = Seq(
    PolicyStatement(
      Effect = "Allow",
      Action = Seq(
        "sns:Publish"
      ),
      Principal = Option(DefinedPrincipal(Map("Service" → Seq("cloudformation.amazonaws.com")))),
      Resource = Option(ResourceRef(topic))
    ),
    PolicyStatement(
      Effect = "Allow",
      Action = Seq(
        "sns:Publish"
      ),
      Principal = Option(DefinedPrincipal(Map("AWS" → Seq(`Fn::Sub`("arn:aws:iam::${AWS::AccountId}:user/bholt"))))),
      Resource = Option(ResourceRef(topic))
    )
  )),
  Topics = Seq(topic)
)
```

I think this might be because `PolicyStatement` is missing a [`Sid`](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Sid) field, because if I manually edit the generated JSON and add `Sid` elements with unique values to each policy statement, the stack creates successfully.

I wondered if someone else is using this successfully, and if so, could share an example of how they do it? If not, is there a reason that `Sid` is not currently part of `PolicyStatement`?

**Comment by bkrodgers** [comment]
I'm guessing the reason we haven't run into this before is this lovely gem from the page you linked:
```Some AWS services (for example, Amazon SQS or Amazon SNS) might require this element and have uniqueness requirements for it.```

Gotta love AWS's consistency!  It's certainly possible we just haven't written SQS or SNS policies with multiple statements here yet and haven't hit this.  Will take a look at your PR soon.
