### ISSUE TITLE
Merge master back into develop?

### ISSUE THREAD

**Issue by ryan-richt** [MonsantoCo/cloudformation-template-generator#16]
Seems like at some point (my fault I'm sure) we had a number of direct-to-master commits, should we merge those back into develop and get back to the standard flow? @ddgenome is that the way to fix it?

**Comment by ryan-richt** [comment]
after that, as @guoshimin pointed out, we should add to README.md, a note about importing TransportProtocol._ to use the fancier parts of the routing DSL

**Comment by ddgenome** [comment]
I recommend we just start developing off master since we seem to be hitting this problem repeatedly. With the sbt release plugin, the whole git-flow develop/master stuff is not truly necessary. I'll work on getting everything onto master, wiring up sbt release if not already present, and cutting a new release.

**Comment by ddgenome** [comment]
Here are the list of commits on master that are not in develop:

```
$ git log master ^develop --no-merges
commit 487494a611ac8d2bfceab73f4af96b1092b5f584
Author: Ryan Richt <ryan-richt@users.noreply.github.com>
Date:   Mon Jul 27 15:08:10 2015 -0500

    doc template.lookupResource new feature, blog post

commit 3b4d73cba3dcfc480ba72e63fc3e87b7c5c868ff
Author: Ryan Richt <ryan-richt@users.noreply.github.com>
Date:   Mon Jul 27 15:00:44 2015 -0500

    Added Eric to MAINTAINERS (really, contributors)

commit 7e4f86bb25237e4c353679f174ad62bd354fbf17
Author: Ryan Richt <ryan-richt@users.noreply.github.com>
Date:   Mon Jul 27 14:59:06 2015 -0500

    added resource support from Eric
```

**Comment by ddgenome** [comment]
Seems this problem was largely our fault, we forgot to make develop the default branch in this repo.

**Comment by ddgenome** [comment]
The merging is complete, https://github.com/MonsantoCo/cloudformation-template-generator/pull/17

For now I am holding off on deleting the develop branch in case anyone has changes/branches based off it.

**Comment by ddgenome** [comment]
This is all complete and a new version, 1.0.6, is on bintray.
