### ISSUE TITLE
Make regions and availability zones objects rather than strings

### ISSUE THREAD

**Issue by ddgenome** [MonsantoCo/cloudformation-template-generator#21]
Something like:

```
sealed trait `AWS::Region`
object `AWS::Region` extends DefaultJsonProtocol {
  case object `AWS::Region::us-east-1` extends `AWS::Region`
  case object `AWS::Region::us-west-1` extends `AWS::Region`
  ...

  implicit val format: JsonFormat[AWSRegions] = new JsonFormat[AWSRegions] {
    override def write(obj: AWSRegions)= JsString(obj.toString)
    override def read(json: JsValue): AWSRegions = {
      json.toString match {
        case "us-east-1"  => `AWS::Region::us-east-1`
        case "us-west-1" => `AWS::Region::us-west-1`
        ...
      }
    }
  }
}
```

**Comment by ddgenome** [comment]
Probably belongs in AmazonFunctionCall.scala.

**Comment by seanmcl** [comment]
This does not seem like a good idea to me. It would require recompilation whenever a new region and az are introduced.

**Comment by bkrodgers** [comment]
If we did this, I think we'd only do it as a convenience and keep the ability to specify one explicitly.   In other words, we might want to have objects for the known regions, but still have a case class that lets you pass in whatever you want to accommodate new regions without a code change.   

Even that isn't high on my priority list.  We're coming up on the two year anniversary of this issue, so I may just close it out.
