### ISSUE TITLE
Add IAM policy to existing role

### ISSUE THREAD

**Issue by DimaRabkin** [MonsantoCo/cloudformation-template-generator#240]
I'm trying to create a cloud formation configuration that adds IAM policies to existing role.
Can i do it with the generator?
`AWS::IAM::Policy` contains `Roles` field as sequence of `ResourceRef[AWS::IAM::Role]` that creates a  reference to role in current configuration: 
```
[
  {"Ref": "..."}
]
```
I want it to generate just:
```
[
 "..."
]

**Comment by seanmcl** [comment]
@DimaRabkin The existing code does not allow you to do that.  I sent a pull request, referenced above.

**Comment by bkrodgers** [comment]
Just released v3.8.1 which includes this fix.  Let me know if you still have issues.
