### ISSUE TITLE
Add EMR support

### ISSUE THREAD

**Issue by ddgenome** [MonsantoCo/cloudformation-template-generator#34]
CloudFormation does not seem to currently support EMR.

**Comment by tj-corrigan** [comment]
now possible per https://aws.amazon.com/about-aws/whats-new/2016/02/aws-cloudformation-adds-support-for-amazon-vpc-nat-gateway-amazon-ec2-container-registry-and-more/

**Comment by tylersouthwick** [comment]
Addressed in https://github.com/MonsantoCo/cloudformation-template-generator/pull/121

**Comment by tj-corrigan** [comment]
Closed by #121.
