### ISSUE TITLE
Fix `Fn::Not`, `Fn::And`, and `Fn::Or`

### ISSUE THREAD

**Issue by bkrodgers** [MonsantoCo/cloudformation-template-generator#60]
In issue https://github.com/MonsantoCo/cloudformation-template-generator/pull/57, our good friend @ddgenome changed `Fn::Not`, `Fn::And`, and `Fn::Or` to require a `ConditionRef`.  As I'm working to update our usage of the library to the new version, I'm now realizing this is not correct.  These functions can accept more than just a `ConditionRef`.  They can accept themselves, along with `Fn::Equals`, in addition to accepting a reference to a defined condition.  For example, a condition that checks if a given parameter is not blank would look like this:

````Fn::Not`(`Fn::Equals`(a = ParameterRef(serviceELBSubdomainNameParameter), b = StringToken("")))```

The only way to make that work in the new model is to define the `equals` as a intermediate condition, even if I don't ever plan to use it, and then define an additional condition for the `Not`.  

Similarly, if you wanted to do a compound condition that nests `And`s and `Or`s together, you'd have to define an intermediate condition for each component of that.  

Of course the easiest "fix" is to back this out and go back to Token[String], but a better solution would be to come up with a type structure that allows the valid types of `Fn::Not`, `Fn::And`, `Fn::Or`, `Fn::Equals`, and `ConditionRef`.  I have to admit that I'm still not quite a master of the type system enough to see exactly how to do this, though I'm trying to figure it out.  @ddgenome or anyone else, if you have thoughts on this, please let me know.

I do believe the change to `Fn::If` is correct, however.  It does require a named condition.

**Comment by bkrodgers** [comment]
It also looks like even with the intermediate condition workaround described above, this doesn't get serialized right here.

It serialized to: 
```
"ServiceELBSubdomainNameIsDefined": {
      "Fn::Not": ["ServiceELBSubdomainNameIsNotDefined"]
    }
```
But should be:
```
"ServiceELBSubdomainNameIsDefined": {
      "Fn::Not": [{"Condition": "ServiceELBSubdomainNameIsNotDefined"}]
    }
```

**Comment by kevinmeredith** [comment]
At a previous job, I had designed the BNF Grammar, and then implemented it in Scala.

As I understand, Brian, the conditions can be nested. Simple example:

```
scala> (4 == 2) && (true || (1 == 1 || 5 == 44) )
res0: Boolean = false
```

Consequently, you need a recursive data structure given that conditionals can be nested.

I believe that it'd be useful to read the "Parser Combinator" section from the [Stairway Book](http://www.artima.com/pins1ed/combinator-parsing.html).

**Comment by bkrodgers** [comment]
#63 only fixes this in the sense that it works again and adds unit tests for the cases that #57 broke.  Leaving this ticket open to add the type safety that #57 intended to add, but with the additional cases we need.  I need to move on for now.

**Comment by bkrodgers** [comment]
Reopened for a future type safe solution -- PR #63 backs out the change and adds unit tests to cover the requirements. 

I had attempted to introduce either a trait or a subtype of AmazonFunctionCall called "ConditionFunctionNestable" to mark the types that can be nested in these condition functions.  However, the whole `Token` and `AmazonFunctionCall` implicit chain broke.  I'm sure it's doable, but I didn't have time.

**Comment by tylersouthwick** [comment]
@bkrodgers My PR handles the tests you created with type safety for `Fn::Not`, `Fn::And`, and `Fn::Or` - are there other situations that we need to have support for?
